version: '3.8'
services:
  kcp:
    image: kcp
    build: 
      context: ./kcp
      dockerfile: Dockerfile
    container_name: kcp
    network_mode: host
    restart: always
    volumes:
      - ./config/kcp.json:/etc/config/kcp.json
    command: ["sh", "-c", "kcp_client -c /etc/config/kcp.json"]

  ss:
    image: shadowsocks/shadowsocks-libev
    container_name: buyvm
    network_mode: host
    volumes:
      - ./config/shadowsocks.json:/etc/config/shadowsocks.json
    # env_file:
    #   - .env
    command: ["sh", "-c", "ss-redir -c /etc/config/shadowsocks.json"]
    restart: always
    # command: ["sh", "-c", "ss-redir -v -s $SS_SERVER -p $SS_SERVER_PORT -b $SS_LOCAL -l $SS_LOCAL_PORT $SS_PARAMETERS"]
